"""Infographic image renderer using Pillow."""

import logging
from datetime import datetime
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from src.config import OUTPUT_DIR
from .templates import CANVAS_WIDTH, CANVAS_HEIGHT, CATEGORY_COLORS

logger = logging.getLogger(__name__)


def _get_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    """Get a font, falling back to default if custom fonts unavailable."""
    try:
        if bold:
            return ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", size, index=1)
        return ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", size)
    except OSError:
        return ImageFont.load_default(size=size)


def generate_infographic(curated_stories: list[dict]) -> Path:
    """Generate an infographic image from curated stories."""
    img = Image.new("RGB", (CANVAS_WIDTH, CANVAS_HEIGHT), "#1A1A2E")
    draw = ImageDraw.Draw(img)

    # Header
    title_font = _get_font(48, bold=True)
    date_font = _get_font(22)
    today = datetime.now().strftime("%B %d, %Y")

    draw.text((60, 50), "AI/ML Daily Digest", font=title_font, fill="#FFFFFF")
    draw.text((60, 110), today, font=date_font, fill="#AAAAAA")

    # Divider
    draw.line([(60, 155), (CANVAS_WIDTH - 60, 155)], fill="#333355", width=2)

    # Stories
    y_offset = 180
    headline_font = _get_font(32, bold=True)
    bullet_font = _get_font(22)

    for story in curated_stories:
        colors = CATEGORY_COLORS.get(story.get("category", "industry"), CATEGORY_COLORS["industry"])

        # Category tag
        tag_font = _get_font(16, bold=True)
        tag_text = story.get("category", "industry").upper()
        draw.rounded_rectangle(
            [(60, y_offset), (60 + len(tag_text) * 11 + 20, y_offset + 28)],
            radius=4,
            fill=colors["primary"],
        )
        draw.text((70, y_offset + 4), tag_text, font=tag_font, fill="#FFFFFF")
        y_offset += 40

        # Headline
        draw.text((60, y_offset), story["headline"][:50], font=headline_font, fill="#FFFFFF")
        y_offset += 45

        # Bullets
        for bullet in story.get("bullets", [])[:3]:
            draw.text((80, y_offset), f"• {bullet[:60]}", font=bullet_font, fill="#CCCCCC")
            y_offset += 32

        y_offset += 30

    # Watermark
    wm_font = _get_font(14)
    draw.text(
        (60, CANVAS_HEIGHT - 40),
        "Generated by AI Infographic Bot",
        font=wm_font,
        fill="#555555",
    )

    # Save
    output_path = OUTPUT_DIR / f"infographic_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
    img.save(output_path, "PNG", quality=95)
    logger.info(f"Saved infographic to {output_path}")
    return output_path
