"""Visual template definitions for LinkedIn infographic posts.

12 templates total: 6 personal + 6 CU Circuits company.
"""

TEMPLATES: dict[str, dict] = {
    # ------------------------------------------------------------------
    # Personal templates (6)
    # ------------------------------------------------------------------
    "dark-glassmorphism": {
        "account": "personal",
        "bg": "#0a0a1a",
        "card_bg": "rgba(255,255,255,0.07)",
        "card_border": "rgba(255,255,255,0.12)",
        "card_radius": 16,
        "text_primary": "#ffffff",
        "text_secondary": "#c0c8e8",
        "text_muted": "#7a85a8",
        "accent_line": "#4f8cff",
        "hook_color": "#4f8cff",
        "insight_bg": "rgba(79,140,255,0.12)",
        "footer_text": "thegeshwar",
    },
    "neon-gradient": {
        "account": "personal",
        "bg": ["#1a0533", "#0a1628"],
        "card_bg": "rgba(191,95,255,0.08)",
        "card_border": "rgba(191,95,255,0.20)",
        "card_radius": 14,
        "text_primary": "#f0e6ff",
        "text_secondary": "#c9a8f0",
        "text_muted": "#8a6aad",
        "accent_line": "#bf5fff",
        "hook_color": "#bf5fff",
        "insight_bg": "rgba(191,95,255,0.12)",
        "footer_text": "thegeshwar",
    },
    "clean-editorial": {
        "account": "personal",
        "bg": "#f8f8f8",
        "card_bg": "#ffffff",
        "card_border": "#e0e0e0",
        "card_radius": 8,
        "text_primary": "#111111",
        "text_secondary": "#444444",
        "text_muted": "#888888",
        "accent_line": "#0066ff",
        "hook_color": "#0066ff",
        "insight_bg": "#e8f0ff",
        "footer_text": "thegeshwar",
    },
    "midnight-teal": {
        "account": "personal",
        "bg": "#0d1117",
        "card_bg": "rgba(45,212,191,0.06)",
        "card_border": "rgba(45,212,191,0.18)",
        "card_radius": 12,
        "text_primary": "#e6edf3",
        "text_secondary": "#8b949e",
        "text_muted": "#484f58",
        "accent_line": "#2dd4bf",
        "hook_color": "#2dd4bf",
        "insight_bg": "rgba(45,212,191,0.10)",
        "footer_text": "thegeshwar",
    },
    "warm-mono": {
        "account": "personal",
        "bg": "#1c1917",
        "card_bg": "rgba(245,158,11,0.07)",
        "card_border": "rgba(245,158,11,0.18)",
        "card_radius": 12,
        "text_primary": "#fafaf9",
        "text_secondary": "#d6d3d1",
        "text_muted": "#78716c",
        "accent_line": "#f59e0b",
        "hook_color": "#f59e0b",
        "insight_bg": "rgba(245,158,11,0.12)",
        "footer_text": "thegeshwar",
    },
    "polar-light": {
        "account": "personal",
        "bg": ["#eef2ff", "#e0e7ff"],
        "card_bg": "#ffffff",
        "card_border": "#c7d2fe",
        "card_radius": 14,
        "text_primary": "#1e1b4b",
        "text_secondary": "#3730a3",
        "text_muted": "#6366f1",
        "accent_line": "#818cf8",
        "hook_color": "#818cf8",
        "insight_bg": "#ede9fe",
        "footer_text": "thegeshwar",
    },

    # ------------------------------------------------------------------
    # CU Circuits company templates (6)
    # ------------------------------------------------------------------
    "circuit-board-dark": {
        "account": "company",
        "bg": "#0a0a0a",
        "card_bg": "#0d1a0d",
        "card_border": "rgba(212,160,23,0.30)",
        "card_radius": 10,
        "text_primary": "#e8f5e8",
        "text_secondary": "#a8c5a8",
        "text_muted": "#5a7a5a",
        "accent_line": "#d4a017",
        "hook_color": "#d4a017",
        "insight_bg": "rgba(212,160,23,0.10)",
        "footer_text": "cucircuits.com",
        "logo": True,
    },
    "copper-navy": {
        "account": "company",
        "bg": "#0c1222",
        "card_bg": "rgba(205,127,50,0.07)",
        "card_border": "rgba(205,127,50,0.22)",
        "card_radius": 12,
        "text_primary": "#f0f4ff",
        "text_secondary": "#a0aac8",
        "text_muted": "#5a6480",
        "accent_line": "#cd7f32",
        "hook_color": "#cd7f32",
        "insight_bg": "rgba(205,127,50,0.12)",
        "footer_text": "cucircuits.com",
        "logo": True,
    },
    "clean-fabrication": {
        "account": "company",
        "bg": "#fafafa",
        "card_bg": "#ffffff",
        "card_border": "#c8e6d4",
        "card_radius": 8,
        "text_primary": "#0a2a1a",
        "text_secondary": "#2d6a4a",
        "text_muted": "#6aab88",
        "accent_line": "#006644",
        "hook_color": "#006644",
        "insight_bg": "#e6f4ec",
        "footer_text": "cucircuits.com",
        "logo": True,
        "grid_pattern": True,
    },
    "solder-mask-blue": {
        "account": "company",
        "bg": ["#002244", "#001133"],
        "card_bg": "rgba(255,255,255,0.06)",
        "card_border": "rgba(255,255,255,0.16)",
        "card_radius": 12,
        "text_primary": "#ffffff",
        "text_secondary": "#b0c8e8",
        "text_muted": "#5a7aa8",
        "accent_line": "#ffffff",
        "hook_color": "#7eb8f7",
        "insight_bg": "rgba(255,255,255,0.08)",
        "footer_text": "cucircuits.com",
        "logo": True,
    },
    "threed-print-orange": {
        "account": "company",
        "bg": "#1a1a1a",
        "card_bg": "rgba(255,102,0,0.07)",
        "card_border": "rgba(255,102,0,0.22)",
        "card_radius": 12,
        "text_primary": "#f5f5f5",
        "text_secondary": "#cccccc",
        "text_muted": "#888888",
        "accent_line": "#ff6600",
        "hook_color": "#ff6600",
        "insight_bg": "rgba(255,102,0,0.12)",
        "footer_text": "cucircuits.com",
        "logo": True,
    },
    "india-tech-gradient": {
        "account": "company",
        "bg": "#111111",
        "card_bg": "rgba(255,153,51,0.07)",
        "card_border": "rgba(255,153,51,0.20)",
        "card_radius": 12,
        "text_primary": "#ffffff",
        "text_secondary": "#e0d0c0",
        "text_muted": "#8a7a6a",
        "accent_line": "#ff9933",
        "hook_color": "#ff9933",
        "insight_bg": "rgba(255,153,51,0.10)",
        "footer_text": "cucircuits.com",
        "logo": True,
        "tricolor_accent": ["#ff9933", "#ffffff", "#138808"],
    },
}


def get_template(name: str) -> dict:
    """Return template dict by name. Raises KeyError if not found."""
    return TEMPLATES[name]


def list_templates(account: str) -> list[str]:
    """Return template names for the given account."""
    return [k for k, v in TEMPLATES.items() if v["account"] == account]
